--
-- Table structure for table `provinces`
--
CREATE TABLE IF NOT EXISTS `provinces` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `addr_citycode` varchar(255) NOT NULL,
  `addr_city` varchar(255) NOT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `addr_citycode` (`addr_citycode`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- --------------------------------------------------------
--
-- Table structure for table `districts`
--
CREATE TABLE IF NOT EXISTS `districts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `province_id` int(11) NOT NULL,
  `addr_districtcode` varchar(255) NOT NULL,
  `addr_district` varchar(255) NOT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `addr_districtcode` (`addr_districtcode`),
  KEY `province_id` (`province_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- --------------------------------------------------------
--
-- Dumping data for table `provinces`
--
INSERT INTO `provinces` (`id`, `addr_citycode`, `addr_city`) VALUES
(1, 'AG', 'An Giang'),
(2, 'BRVT', 'Bà Rịa Vũng Tàu'),
(3, 'BC', 'Bắc Cạn'),
(4, 'BG', 'Bắc Giang'),
(5, 'BL', 'Bạc Liêu'),
(6, 'BN', 'Bắc Ninh'),
(7, 'BT', 'Bến Tre'),
(8, 'BH', 'Bình Định'),
(9, 'BD', 'Bình Dương'),
(10, 'BP', 'Bình Phước'),
(11, 'BTN', 'Bình Thuận'),
(12, 'CM', 'Cà Mau'),
(13, 'CT', 'Cần Thơ'),
(14, 'CB', 'Cao Bằng'),
(15, '003', 'Đà Nẵng'),
(16, 'DL', 'Đăk Lăk'),
(17, 'DG', 'Đăk Nông'),
(18, 'DB', 'Điện Biên'),
(19, 'DN', 'Đồng Nai'),
(20, 'DT', 'Đồng Tháp'),
(21, 'GL', 'Gia Lai'),
(22, 'HGG', 'Hà Giang'),
(23, 'HN', 'Hà Nam'),
(24, '002', 'Hà Nội'),
(25, 'HAT', 'Hà Tĩnh'),
(26, 'HD', 'Hải Dương'),
(27, 'HP', 'Hải Phòng'),
(28, 'HG', 'Hậu Giang'),
(29, '001', 'Hồ Chí Minh'),
(30, 'HB', 'Hòa Bình'),
(31, 'HY', 'Hưng Yên'),
(32, 'KH', 'Khánh Hòa'),
(33, 'KG', 'Kiên Giang'),
(34, 'KT', 'Kon Tum'),
(35, 'LC', 'Lai Châu'),
(36, 'LD', 'Lâm Đồng'),
(37, 'LS', 'Lạng Sơn'),
(38, 'LI', 'Lào Cai'),
(39, 'LA', 'Long An'),
(40, 'ND', 'Nam Định'),
(41, 'NA', 'Nghệ An'),
(42, 'NB', 'Ninh Bình'),
(43, 'NT', 'Ninh Thuận'),
(44, 'PT', 'Phú Thọ'),
(45, 'PY', 'Phú Yên'),
(46, 'QB', 'Quảng Bình'),
(47, 'QM', 'Quảng Nam'),
(48, 'QI', 'Quảng Ngãi'),
(49, 'QN', 'Quảng Ninh'),
(50, 'QT', 'Quảng Trị'),
(51, 'ST', 'Sóc Trăng'),
(52, 'SL', 'Sơn La'),
(53, 'TN', 'Tây Ninh'),
(54, 'TB', 'Thái Bình'),
(55, 'THN', 'Thái Nguyên'),
(56, 'TH', 'Thanh Hóa'),
(57, 'TTH', 'Thừa Thiên Huế'),
(58, 'TG', 'Tiền Giang'),
(59, 'TV', 'Trà Vinh'),
(60, 'TQ', 'Tuyên Quang'),
(61, 'VL', 'Vĩnh Long'),
(62, 'VP', 'Vĩnh Phúc'),
(63, 'YB', 'Yên Bái');

-- --------------------------------------------------------
--
-- Dumping data for table `districts`
--
INSERT INTO `districts` (`province_id`, `addr_districtcode`, `addr_district`) VALUES
(1,"AG.AP","H. An Phú"),
(1,"AG.CP","H. Châu Phú"),
(1,"AG.CT","H. Châu Thành"),
(1,"AG.CM","H. Chợ Mới"),
(1,"AG.PT","H. Phú Tân"),
(1,"AG.TS","H. Thoại Sơn"),
(1,"AG.TB","H. Tịnh Biên"),
(1,"AG.TT","H. Tri Tôn"),
(1,"AG.VT","H. Vĩnh Trinh"),
(1,"AG.TP.CD","TP. Châu Đốc"),
(1,"AG.TP.LX","TP. Long Xuyên"),
(1,"AG.TX.TC","TX. Tân Châu"),
(2,"BRVT.CD","H. Châu Đức"),
(2,"BRVT.COD","H. Côn Đảo"),
(2,"BRVT.DD","H. Đất Đỏ"),
(2,"BRVT.LD","H. Long Đất"),
(2,"BRVT.LL","H. Long Điền"),
(2,"BRVT.TT","H. Tân Thành"),
(2,"BRVT.XM","H. Xuyên Mộc"),
(2,"BRVT.TP.BR","TP. Bà Rịa"),
(2,"BRVT.TP.VT","TP. Vũng Tàu"),
(2,"BRVT.TX.PM","TX. Phú Mỹ"),
(3,"BC.BB","H. Ba Bể"),
(3,"BC.BT","H. Bạch Thông"),
(3,"BC.CD","H. Chợ Đồn"),
(3,"BC.CM","H. Chợ Mới"),
(3,"BC.NR","H. Na Rì"),
(3,"BC.NS","H. Ngân Sơn"),
(3,"BC.PN","H. Pắc Nặm"),
(3,"BC.TX.BC","TX. Bắc Cạn"),
(4,"BG.HH","H. Hiệp Hòa"),
(4,"BG.LG","H. Lạng Giang"),
(4,"BG.LM","H. Lục Nam"),
(4,"BG.LN","H. Lục Ngạn"),
(4,"BG.SD","H. Sơn Động"),
(4,"BG.TY","H. Tân Yên"),
(4,"BG.VY","H. Việt Yên"),
(4,"BG.YD","H. Yên Dũng"),
(4,"BG.YT","H. Yên Thế"),
(4,"BG.TP.BG","TP. Bắc Giang"),
(5,"BL.DH","H. Đông Hải"),
(5,"BL.HB","H. Hòa Bình"),
(5,"BL.HD","H. Hồng Dân"),
(5,"BL.PL","H. Phước Long"),
(5,"BL.TT","H. Thạnh Trị"),
(5,"BL.VL","H. Vĩnh Lợi"),
(5,"BL.TP.BL","TP. Bạc Liêu"),
(5,"BL.TX.GR","TX. Giá Rai"),
(6,"BN.GB","H. Gia Bình"),
(6,"BN.LT","H. Lương Tài"),
(6,"BN.QV","H. Quế Võ"),
(6,"BN.TT","H. Thuận Thành"),
(6,"BN.TD","H. Tiên Du"),
(6,"BN.YP","H. Yên Phong"),
(6,"BN.TP.BN","TP. Bắc Ninh"),
(6,"BN.TX.TS","TX. Từ Sơn"),
(7,"BT.BT","H. Ba Tri"),
(7,"BT.BD","H. Bình Đại"),
(7,"BT.CT","H. Châu Thành"),
(7,"BT.CL","H. Chợ Lách"),
(7,"BT.GT","H. Giồng Trôm"),
(7,"BT.MCB","H. Mỏ Cày Bắc"),
(7,"BT.MCN","H. Mỏ Cày Nam"),
(7,"BT.TP","H. Thạnh Phú"),
(7,"BT.TP.BT","TP. Bến Tre"),
(8,"BH.AL","H. An Lão"),
(8,"BH.AN","H. An Nhơn"),
(8,"BH.CB","H. Cư Bang"),
(8,"BH.HA","H. Hoài Ân"),
(8,"BH.HN","H. Hoài Nhơn"),
(8,"BH.PC","H. Phù Cát"),
(8,"BH.PM","H. Phù Mỹ"),
(8,"BH.TS","H. Tây Sơn"),
(8,"BH.TP","H. Tuy Phước"),
(8,"BH.VC","H. Vân Canh"),
(8,"BH.VT","H. Vĩnh Thạnh"),
(8,"BH.TP.QN","TP. Quy Nhơn"),
(8,"BH.TX.AN","TX. An Nhơn"),
(9,"BD.BTU","H. Bắc Tân Uyên"),
(9,"BD.BB","H. Bàu Bàng"),
(9,"BD.DT","H. Dầu Tiếng"),
(9,"BD.LT","H. Lái Thiêu"),
(9,"BD.PG","H. Phú Giáo"),
(9,"BD.TA","H. Thuận An"),
(9,"BD.TP.M","TP. Mới"),
(9,"BD.TP.TD","TP. Thủ Dầu Một"),
(9,"BD.TX.BC","TX. Bến Cát"),
(9,"BD.TX.DA","TX. Dĩ An"),
(9,"BD.TX.TU","TX. Tân Uyên"),
(9,"BD.TX.TA","TX. Thuận An"),
(10,"BP.BD","H. Bù Đăng"),
(10,"BP.BP","H. Bù Đốp"),
(10,"BP.BGM","H. Bù Gia Mập"),
(10,"BP.TT","H. Chơn Thành"),
(10,"BP.DP","H. Đồng Phú"),
(10,"BP.HQ","H. Hớn Quản"),
(10,"BP.LN","H. Lộc Ninh"),
(10,"BP.PR","H. Phú Riềng"),
(10,"BP.TX.BL","TX. Bình Long"),
(10,"BP.TX.DX","TX. Đồng Xoài"),
(10,"BP.TX.PL","TX. Phước Long"),
(11,"BTN.BB","H. Bắc Bình"),
(11,"BTN.DL","H. Đức Linh"),
(11,"BTN.HT","H. Hàm Tân"),
(11,"BTN.HTB","H. Hàm Thuận Bắc"),
(11,"BTN.HTN","H. Hàm Thuận Nam"),
(11,"BTN.PQ","H. Phú Quý"),
(11,"BTN.TL","H. Tánh Linh"),
(11,"BTN.TP","H. Tuy Phong"),
(11,"BTN.TP.PT","TP. Phan Thiết"),
(11,"BTN.TX.LG","TX. La Gi"),
(12,"CM.CN","H. Cái Nước"),
(12,"CM.DD","H. Đầm Dơi"),
(12,"CM.NC","H. Năm Căn"),
(12,"CM.NH","H. Ngọc Hiển"),
(12,"CM.PT","H. Phú Tân"),
(12,"CM.TB","H. Thới Bình"),
(12,"CM.TVT","H. Trần Văn Thời"),
(12,"CM.UM","H. U Minh"),
(12,"CM.TP.CM","TP. Cà Mau"),
(13,"CT.CD","H. Cờ Đỏ"),
(13,"CT.PD","H. Phong Điền"),
(13,"CT.TL","H. Thới Lai"),
(13,"CT.VT","H. Vĩnh Thạnh"),
(13,"CT.BT","Q. Bình Thủy"),
(13,"CT.CR","Q. Cái Răng"),
(13,"CT.NK","Q. Ninh Kiều"),
(13,"CT.OM","Q. Ô Môn"),
(13,"CT.TN","Q. Thốt Nốt"),
(14,"CB.BL","H. Bảo Lạc"),
(14,"CB.BLM","H. Bảo Lâm"),
(14,"CB.HL","H. Hạ Lang"),
(14,"CB.HQ","H. Hà Quảng"),
(14,"CB.HA","H. Hòa An"),
(14,"CB.NB","H. Nguyên Bình"),
(14,"CB.PH","H. Phục Hòa"),
(14,"CB.QU","H. Quảng Uyên"),
(14,"CB.TA","H. Thạch An"),
(14,"CB.TN","H. Thông Nông"),
(14,"CB.TL","H. Trà Lĩnh"),
(14,"CB.TK","H. Trùng Khánh"),
(14,"CB.TP.CB","TP. Cao Bằng"),
(15,"003.HV","H. Hòa Vang"),
(15,"003.HS","H. Hoàng Sa"),
(15,"003.CL","Q. Cẩm Lệ"),
(15,"003.HC","Q. Hải Châu"),
(15,"003.LC","Q. Liên Chiểu"),
(15,"003.NHS","Q. Ngũ Hành Sơn"),
(15,"003.ST","Q. Sơn Trà"),
(15,"003.TK","Q. Thanh Khê"),
(16,"DL.BD","H. Buôn Đôn"),
(16,"DL.CK","H. Cư Kuin"),
(16,"DL.CM","H. Cư M'Gar"),
(16,"DL.EL","H. Ea H'Leo"),
(16,"DL.EK","H. Ea Kar"),
(16,"DL.ES","H. EA Súp"),
(16,"DL.KA","H. Krông Ana"),
(16,"DL.KB","H. Krông Bông"),
(16,"DL.KK","H. Krông Buk"),
(16,"DL.FN","H. Krông Năng"),
(16,"DL.KP","H. Krông Pắc"),
(16,"DL.L","H. Lăk"),
(16,"DL.MD","H. M'Đrăk"),
(16,"DL.TP.BM","TP. Buôn Ma Thuột"),
(16,"DL.BH","TX. Buôn Hồ"),
(17,"DG.CJ","H. Cư Jut"),
(17,"DG.DG","H. Đăk GLong"),
(17,"DG.DM","H. Đăk Mil"),
(17,"DG.GL","H. Đăk R'Lấp"),
(17,"DG.DS","H. Đăk Song"),
(17,"DG.KN","H. Krông Nô"),
(17,"DG.TD","H. Tuy Đức"),
(17,"DG.TX.GN","TX. Gia Nghĩa"),
(18,"DB.DB","H. Điện Biên"),
(18,"DB.DBD","H. Điện Biên Đông"),
(18,"DB.MA","H. Mường Ảng"),
(18,"DB.MC","H. Mường Chà"),
(18,"DB.MN","H. Mường Nhé"),
(18,"DB.NP","H. Nậm Pồ"),
(18,"DB.TU","H. Thanh Uyên"),
(18,"DB.TC","H. Tủa Chùa"),
(18,"DB.TG","H. Tuần Giáo"),
(18,"DB.TP.DB","TP. Điện Biên"),
(18,"DB.TX.ML","TX. Mường Lay"),
(19,"DN.CM","H. Cẩm Mỹ"),
(19,"DN.DQ","H. Định Quán"),
(19,"DN.LT","H. Long Thành"),
(19,"DN.NT","H. Nhơn Trạch"),
(19,"DN.TP","H. Tân Phú"),
(19,"DN.TN","H. Thống Nhất"),
(19,"DN.TB","H. Trảng Bom"),
(19,"DN.VC","H. Vĩnh Cửu"),
(19,"DN.XL","H. Xuân Lộc"),
(19,"DN.TP.BH","TP. Biên Hòa"),
(19,"DN.TX.LK","TX. Long Khánh"),
(20,"DT.CL","H. Cao Lãnh"),
(20,"DT.CT","H. Châu Thành"),
(20,"DT.HH","H. Hồng Hạnh"),
(20,"DT.HN","H. Hồng Ngự"),
(20,"DT.LV","H. Lai Vung"),
(20,"DT.LO","H. Lấp Vò"),
(20,"DT.TN","H. Tam Nông"),
(20,"DT.TH","H. Tân Hồng"),
(20,"DT.TB","H. Thanh Bình"),
(20,"DT.TM","H. Tháp Mười"),
(20,"DT.TP.CL","TP. Cao Lãnh"),
(20,"DT.TP.SD","TP. Sa Đéc"),
(20,"DT.TX.HN","TX. Hồng Ngự"),
(21,"GL.CP","H. Chư Păh"),
(21,"GL.CG","H. Chư Prông"),
(21,"GL.CPU","H. Chư Pưh"),
(21,"GL.CS","H. Chư Sê"),
(21,"GL.DD","H. Đăk Đoa"),
(21,"GL.DP","H. Đăk Pơ"),
(21,"GL.DC","H. Đức Cơ"),
(21,"GL.IG","H. Ia Grai"),
(21,"GL.IP","H. Ia Pa"),
(21,"GL.K","H. K'Bang"),
(21,"GL.KC","H. Kông Chro"),
(21,"GL.KP","H. Krông Pa"),
(21,"GL.MY","H. Mang Yang"),
(21,"GL.PT","H. Phú Thiện"),
(21,"GL.TP.P","TP. Pleiku"),
(21,"GL.TX.AYP","TX. A Yun Pa"),
(21,"GL.TX.AK","TX. An Khê"),
(22,"HGG.BM","H. Bắc Mê"),
(22,"HGG.BQ","H. Bắc Quang"),
(22,"HGG.DV","H. Đồng Văn"),
(22,"HGG.HSP","H. Hoàng Su Phì"),
(22,"HGG.MV","H. Mèo Vạc"),
(22,"HGG.QB","H. Quản Bạ"),
(22,"HGG.QH","H. Quang Bình"),
(22,"HGG.VX","H. Vị Xuyên"),
(22,"HGG.XM","H. Xín Mần"),
(22,"HGG.YM","H. Yên Minh"),
(22,"HGG.TP.HG","TP. Hà Giang"),
(23,"HN.BL","H. Bình Lục"),
(23,"HN.DT","H. Duy Tiên"),
(23,"HN.KB","H. Kim Bảng"),
(23,"HN.LN","H. Lý Nhân"),
(23,"HN.TL","H. Thanh Liêm"),
(23,"HN.TP.PL","TP. Phủ Lý"),
(24,"002.BV","H. Ba Vì"),
(24,"002.CM","H. Chương Mỹ"),
(24,"002.DP","H. Đan Phượng"),
(24,"002.DA","H. Đông Anh"),
(24,"002.GL","H. Gia Lâm"),
(24,"002.HD","H. Hoài Đức"),
(24,"002.ML","H. Mê Linh"),
(24,"002.MD","H. Mỹ Đức"),
(24,"002.PX","H. Phú Xuyên"),
(24,"002.PT","H. Phúc Thọ"),
(24,"002.QO","H. Quốc Oai"),
(24,"002.SS","H. Sóc Sơn"),
(24,"002.HTT","H. Thạch Thất"),
(24,"002.TO","H. Thanh Oai"),
(24,"002.TT","H. Thanh Trì"),
(24,"002.THT","H. Thường Tín"),
(24,"002.TL","H. Từ Liêm"),
(24,"002.UH","H. ứng Hòa"),
(24,"002.BD","Q. Ba Đình"),
(24,"002.BTL","Q. Bắc Từ Liêm"),
(24,"002.CG","Q. Cầu Giấy"),
(24,"002.DD","Q. Đống Đa"),
(24,"002.QHD","Q. Hà Đông"),
(24,"002.HBT","Q. Hai Bà Trưng"),
(24,"002.HK","Q. Hoàn Kiếm"),
(24,"002.HM","Q. Hoàng Mai"),
(24,"002.LB","Q. Long Biên"),
(24,"002.NTL","Q. Nam Từ Liêm"),
(24,"002.TH","Q. Tây Hồ"),
(24,"002.TX","Q. Thanh Xuân"),
(24,"002.TX.ST","TX. Sơn Tây"),
(25,"HAT.CX","H. Cẩm Xuyên"),
(25,"HAT.CL","H. Can Lộc"),
(25,"HAT.DT","H. Đức Thọ"),
(25,"HAT.HK","H. Hương Khê"),
(25,"HAT.HS","H. Hương Sơn"),
(25,"HAT.LH","H. Lộc Hà"),
(25,"HAT.NX","H. Nghi Xuân"),
(25,"HAT.TH","H. Thạch Hà"),
(25,"HAT.VQ","H. Vũ Quang"),
(25,"HAT.TP.HT","Tp. Hà Tĩnh"),
(25,"HAT.TX.HL","TX. Hồng Lĩnh"),
(25,"HAT.TX.KA","TX. Kỳ Anh"),
(26,"HD.BG","H. Bình Giang"),
(26,"HD.CG","H. Cẩm Giàng"),
(26,"HD.GL","H. Gia Lộc"),
(26,"HD.KT","H. Kim Thành"),
(26,"HD.KM","H. Kinh Môn"),
(26,"HD.NS","H. Nam Sách"),
(26,"HD.NG","H. Ninh Giang"),
(26,"HD.TH","H. Thanh Hà"),
(26,"HD.TM","H. Thanh Miện"),
(26,"HD.TK","H. Tứ Kỳ"),
(26,"HD.TP.HD","TP. Hải Dương"),
(26,"HD.TX.CL","TX. Chí Linh"),
(27,"HP.AD","H. An Dương"),
(27,"HP.AN","H. An Hải"),
(27,"HP.AL","H. An Lão"),
(27,"HP.BLV","H. Bạch Long Vĩ"),
(27,"HP.CH","H. Cát Hải"),
(27,"HP.KT","H. Kiến Thụy"),
(27,"HP.TN","H. Thủy Nguyên"),
(27,"HP.TL","H. Tiên Lãng"),
(27,"HP.VB","H. Vĩnh Bảo"),
(27,"HP.DS","Q. Đồ Sơn"),
(27,"HP.DK","Q. Dương Kinh"),
(27,"HP.HA","Q. Hải An"),
(27,"HP.HB","Q. Hồng Bàng"),
(27,"HP.KA","Q. Kiến An"),
(27,"HP.LC","Q. Lê Chân"),
(27,"HP.NQ","Q. Ngô Quyền"),
(28,"HG.CT","H. Châu Thành"),
(28,"HG.CTA","H. Châu Thành A"),
(28,"HG.PH","H. Phụng Hiệp"),
(28,"HG.VT","H. Vị Thủy"),
(28,"HG.TP.VT","TP. Vị Thanh"),
(28,"HG.TX.LM","TX. Long Mỹ"),
(28,"HG.TX.NB","TX. Ngã Bảy"),
(29,"001.BC","H. Bình Chánh"),
(29,"001.CG","H. Cần Giờ"),
(29,"001.CC","H. Củ Chi"),
(29,"001.HM","H. Hóc Môn"),
(29,"001.NB","H. Nhà Bè"),
(29,"001.01","Q. 1"),
(29,"001.10","Q. 10"),
(29,"001.11","Q. 11"),
(29,"001.12","Q. 12"),
(29,"001.02","Q. 2"),
(29,"001.03","Q. 3"),
(29,"001.04","Q. 4"),
(29,"001.05","Q. 5"),
(29,"001.06","Q. 6"),
(29,"001.07","Q. 7"),
(29,"001.08","Q. 8"),
(29,"001.09","Q. 9"),
(29,"001.BB","Q. Bình Tân"),
(29,"001.BT","Q. Bình Thạnh"),
(29,"001.GV","Q. Gò Vấp"),
(29,"001.PN","Q. Phú Nhuận"),
(29,"001.TB","Q. Tân Bình"),
(29,"001.TP","Q. Tân Phú"),
(29,"001.TD","Q. Thủ Đức"),
(30,"HB.CP","H. Cao Phong"),
(30,"HB.DB","H. Đà Bắc"),
(30,"HB.KB","H. Kim Bôi"),
(30,"HB.KS","H. Kỳ Sơn"),
(30,"HB.LS","H. Lạc Sơn"),
(30,"HB.LT","H. Lạc Thủy"),
(30,"HB.LN","H. Lương Sơn"),
(30,"HB.MC","H. Mai Châu"),
(30,"HB.TL","H. Tân Lạc"),
(30,"HB.YT","H. Yên Thủy"),
(30,"HB.TP.HB","Tp. Hòa Bình"),
(31,"HY.AT","H. Ân Thi"),
(31,"HY.KC","H. Khoái Châu"),
(31,"HY.KD","H. Kim Động"),
(31,"HY.MH","H. Mỹ Hào"),
(31,"HY.PC","H. Phù Cừ"),
(31,"HY.TL","H. Tiên Lữ"),
(31,"HY.VG","H. Văn Giang"),
(31,"HY.VL","H. Văn Lâm"),
(31,"HY.YM","H. Yên Mỹ"),
(31,"HY.TP.HY","TP. Hưng Yên"),
(32,"KH.CL","H. Cam Lâm"),
(32,"KH.DK","H. Diên Khánh"),
(32,"KH.KS","H. Khánh Sơn"),
(32,"KH.KV","H. Khánh Vĩnh"),
(32,"KH.TS","H. Trường Sa"),
(32,"KH.VN","H. Vạn Ninh"),
(32,"KH.TP.CR","TP. Cam Ranh"),
(32,"KH.TP.NT","TP. Nha Trang"),
(32,"KH.TX.NH","TX. Ninh Hòa"),
(33,"KG.AB","H. An Biên"),
(33,"KG.AM","H. An Minh"),
(33,"KG.CT","H. Châu Thành"),
(33,"KG.GT","H. Giang Thành"),
(33,"KG.GR","H. Giồng Riềng"),
(33,"KG.GQ","H. Gò Quao"),
(33,"KG.HD","H. Hòn Đất"),
(33,"KG.KB","H. Kiên Biên"),
(33,"KG.KH","H. Kiên Hải"),
(33,"KG.KL","H. Kiên Lương"),
(33,"KG.PQ","H. Phú Quốc"),
(33,"KG.TH","H. Tân Hiệp"),
(33,"KG.UMT","H. U Minh Thượng"),
(33,"KG.VT","H. Vĩnh Thuận"),
(33,"KG.RG","TP. Rạch Giá"),
(33,"KG.TX.HT","TX. Hà Tiên"),
(34,"KT.DG","H. Đăk Glei"),
(34,"KT.DH","H. Đăk Hà"),
(34,"KT.DT","H. Đăk Tô"),
(34,"KT.IH","H. Ia H'Drai"),
(34,"KT.KP","H. Kon Plông"),
(34,"KT.KR","H. Kông Rẫy"),
(34,"KT.NH","H. Ngọc Hồi"),
(34,"KT.ST","H. Sa Thầy"),
(34,"KT.TM","H. Tu Mơ Rông"),
(34,"KT.TP.KT","TP. Kon Tum"),
(35,"LC.MT","H. Mường Tè"),
(35,"LC.NN","H. Nậm Nhùn"),
(35,"LC.PT","H. Phong Thổ"),
(35,"LC.SH","H. Sìn Hồ"),
(35,"LC.TD","H. Tam Đường"),
(35,"LC.TU","H. Tân Uyên"),
(35,"LC.TY","H. Than Uyên"),
(35,"LC.TP.LC","TP. Lai Châu"),
(36,"LD.BL","H. Bảo Lâm"),
(36,"LD.CT","H. Cát Tiên"),
(36,"LD.DH","H. Đạ Huoai"),
(36,"LD.DT","H. Đạ Tẻh"),
(36,"LD.DR","H. Đam Rông"),
(36,"LD.DL","H. Di Linh"),
(36,"LD.DD","H. Đơn Dương"),
(36,"LD.DG","H. Đức Trọng"),
(36,"LD.LD","H. Lạc Dương"),
(36,"LD.LH","H. Lâm Hà"),
(36,"LD.TP.BL","TP. Bảo Lộc"),
(36,"LD.TP.DL","TP. Đà Lạt"),
(37,"LS.BS","H. Bắc Sơn"),
(37,"LS.BG","H. Bình Gia"),
(37,"LS.CL","H. Cao Lộc"),
(37,"LS.CG","H. Chi Lăng"),
(37,"LS.DL","H. Đình Lập"),
(37,"LS.HL","H. Hữu Lũng"),
(37,"LS.LB","H. Lộc Bình"),
(37,"LS.TD","H. Tràng Định"),
(37,"LS.VL","H. Văn Lãng"),
(37,"LS.VQ","H. Văn Quan"),
(37,"LS.TP.LS","TP. Lạng Sơn"),
(38,"LI.BH","H. Bắc Hà"),
(38,"LI.BT","H. Bảo Thắng"),
(38,"LI.BY","H. Bảo Yên"),
(38,"LI.BX","H. Bát Xát"),
(38,"LI.MK","H. Mường Khương"),
(38,"LI.SP","H. Sa Pa"),
(38,"LI.SMC","H. Si Ma Cai"),
(38,"LI.VB","H. Văn Bàn"),
(38,"LI.TP.LC","TP. Lào Cai"),
(39,"LA.BL","H. Bến Lức"),
(39,"LA.CD","H. Cần Đước"),
(39,"LA.CG","H. Cần Giuộc"),
(39,"LA.CT","H. Châu Thành"),
(39,"LA.DH","H. Đức Hòa"),
(39,"LA.DE","H. Đức Huệ"),
(39,"LA.MH","H. Mộc Hóa"),
(39,"LA.TH","H. Tân Hưng"),
(39,"LA.TT","H. Tân Thạnh"),
(39,"LA.TU","H. Tân Trụ"),
(39,"LA.TA","H. Thạnh Hóa"),
(39,"LA.TTA","H. Thủ Thừa"),
(39,"LA.VH","H. Vĩnh Hưng"),
(39,"LA.TP.TA","TP. Tân An"),
(39,"LA.TX.KT","TX. Kiến Tường"),
(40,"ND.GT","H. Giao Thủy"),
(40,"ND.HH","H. Hải Hậu"),
(40,"ND.ML","H. Mỹ Lộc"),
(40,"ND.NT","H. Nam Trực"),
(40,"ND.NH","H. Nghĩa Hưng"),
(40,"ND.TN","H. Trực Ninh"),
(40,"ND.VB","H. Vụ Bản"),
(40,"ND.XT","H. Xuân Trường"),
(40,"ND.YY","H. ý Yên"),
(40,"ND.TP.ND","TP. Nam Định"),
(41,"NA.AS","H. Anh Sơn"),
(41,"NA.CC","H. Con Cuông"),
(41,"NA.DC","H. Diễn Châu"),
(41,"NA.DL","H. Đô Lương"),
(41,"NA.HN","H. Hưng Nguyên"),
(41,"NA.KS","H. Kỳ Sơn"),
(41,"NA.ND","H. Nam Đàn"),
(41,"NA.NL","H. Nghi Lộc"),
(41,"NA.NGD","H. Nghĩa Đàn"),
(41,"NA.QP","H. Quế Phong"),
(41,"NA.QC","H. Quỳ Châu"),
(41,"NA.QH","H. Quỳ Hợp"),
(41,"NA.QL","H. Quỳnh Lưu"),
(41,"NA.TK","H. Tân Kỳ"),
(41,"NA.TQ","H. Tân Quỳ"),
(41,"NA.TC","H. Thanh Chương"),
(41,"NA.TD","H. Tương Dương"),
(41,"NA.YT","H. Yên Thành"),
(41,"NA.TP.V","TP. Vinh"),
(41,"NA.CL","TX. Cửa Lò"),
(41,"NA.TX.HM","TX. Hoàng Mai"),
(41,"NA.TX.TH","TX. Thái Hòa"),
(42,"NB.GV","H. Gia Viễn"),
(42,"NB.HL","H. Hoa Lư"),
(42,"NB.KS","H. Kim Sơn"),
(42,"NB.NQ","H. Nho Quan"),
(42,"NB.YK","H. Yên Khánh"),
(42,"NB.YM","H. Yên Mô"),
(42,"NB.TP.NB","TP. Ninh Bình"),
(42,"NB.TP.TD","TP. Tam Điệp"),
(42,"NB.TX.NB","TX. Ninh Bình"),
(43,"NT.BA","H. Bác ái"),
(43,"NT.NH","H. Ninh Hải"),
(43,"NT.NP","H. Ninh Phước"),
(43,"NT.NS","H. Ninh Sơn"),
(43,"NT.TB","H. Thuận Bắc"),
(43,"NT.TN","H. Thuận Nam"),
(43,"NT.TP.PRTC","TP. Phan Rang Tháp Chàm"),
(44,"PT.CK","H. Cẩm Khê"),
(44,"PT.DH","H. Đoan Hùng"),
(44,"PT.HH","H. Hạ Hòa"),
(44,"PT.LT","H. Lâm Thao"),
(44,"PT.PN","H. Phù Ninh"),
(44,"PT.ST","H. Sông Thao"),
(44,"PT.TN","H. Tam Nông"),
(44,"PT.TAS","H. Tân Sơn"),
(44,"PT.TB","H. Thanh Ba"),
(44,"PT.TS","H. Thanh Sơn"),
(44,"PT.TT","H. Thanh Thủy"),
(44,"PT.YL","H. Yên Lập"),
(44,"PT.TP.VT","TP. Việt Trì"),
(44,"PT.TX.PT","TX. Phú Thọ"),
(45,"PY.DH","H. Đông Hòa"),
(45,"PY.DX","H. Đồng Xuân"),
(45,"PY.PH","H. Phú Hòa"),
(45,"PY.SA","H. Sơn Hòa"),
(45,"PY.SH","H. Sông Hinh"),
(45,"PY.THA","H. Tây Hòa"),
(45,"PY.TA","H. Tuy An"),
(45,"PY.TP.TH","TP. Tuy Hòa"),
(45,"PY.TX.SC","TX. Sông Cầu"),
(46,"QB.BT","H. Bố Trạch"),
(46,"QB.LT","H. Lệ Thủy"),
(46,"QB.MH","H. Minh Hóa"),
(46,"QB.QN","H. Quảng Ninh"),
(46,"QB.QT","H. Quảng Trạch"),
(46,"QB.TH","H. Tuyên Hóa"),
(46,"QB.TP.DH","TP. Đồng Hới"),
(46,"QB.TX.BD","TX. Ba Đồn"),
(47,"QM.BTM","H. Bắc Trà My"),
(47,"QM.DL","H. Đại Lộc"),
(47,"QM.DG","H. Đông Giang"),
(47,"QM.DX","H. Duy Xuyên"),
(47,"QM.HD","H. Hiệp Đức"),
(47,"QM.NG","H. Nam Giang"),
(47,"QM.NTM","H. Nam Trà My"),
(47,"QM.NS","H. Nông Sơn"),
(47,"QM.NT","H. Núi Thành"),
(47,"QM.PN","H. Phú Ninh"),
(47,"QM.PS","H. Phước Sơn"),
(47,"QM.QS","H. Quế Sơn"),
(47,"QM.TG","H. Tây Giang"),
(47,"QM.TB","H. Thăng Bình"),
(47,"QM.TP","H. Tiên Phước"),
(47,"QM.TP.HA","TP. Hội An"),
(47,"QM.TP.TK","TP. Tam Kỳ"),
(47,"QM.TX.DB","TX. Điện Bàn"),
(48,"QI.BT","H. Ba Tơ"),
(48,"QI.BS","H. Bình Sơn"),
(48,"QI.DP","H. Đức Phổ"),
(48,"QI.LS","H. Lý Sơn"),
(48,"QI.ML","H. Minh Long"),
(48,"QI.MD","H. Mộ Đức"),
(48,"QI.NH","H. Nghĩa Hành"),
(48,"QI.SH","H. Sơn Hà"),
(48,"QI.ST","H. Sơn Tây"),
(48,"QI.SOT","H. Sơn Tịnh"),
(48,"QI.TT","H. Tây Trà"),
(48,"QI.TB","H. Trà Bồng"),
(48,"QI.TN","H. Tư Nghĩa"),
(48,"QI.TP.QN","TP. Quảng Ngãi"),
(49,"QN.BC","H. Ba Chẽ"),
(49,"QN.BL","H. Bình Liêu"),
(49,"QN.CT","H. Cô Tô"),
(49,"QN.DH","H. Đầm Hà"),
(49,"QN.DT","H. Đông Triều"),
(49,"QN.HH","H. Hải Hà"),
(49,"QN.HB","H. Hoành Bồ"),
(49,"QN.TY","H. Tiên Yên"),
(49,"QN.VD","H. Vân Đồn"),
(49,"QN.TP.CP","TP. Cẩm Phả"),
(49,"QN.TP.HL","TP. Hạ Long"),
(49,"QN.TP.HG","TP. Hòn Gai"),
(49,"QN.TP.MC","TP. Móng Cái"),
(49,"QN.TP.UB","TP. Uông Bí"),
(49,"QN.TX.QY","TX. Quảng Yên"),
(50,"QT.CL","H. Cam Lộ"),
(50,"QT.CC","H. Cổn Cỏ"),
(50,"QT.D","H. Đakrông"),
(50,"QT.GL","H. Gio Linh"),
(50,"QT.HL","H. Hải Lăng"),
(50,"QT.HH","H. Hướng Hóa"),
(50,"QT.TP","H. Triệu Phong"),
(50,"QT.VL","H. Vĩnh Linh"),
(50,"QT.TP.DH","TP. Đông Hà"),
(50,"QT.TX.QT","TX. Quảng Trị"),
(51,"ST.CD","H. Cần Đề"),
(51,"ST.CT","H. Châu Thành"),
(51,"ST.CLD","H. Cù Lao Dung"),
(51,"ST.HM","H. Hòa Mỹ"),
(51,"ST.KS","H. Kế Sách"),
(51,"ST.LP","H. Long Phú"),
(51,"ST.MT","H. Mỹ Tú"),
(51,"ST.MX","H. Mỹ Xuyên"),
(51,"ST.TT","H. Thạnh Trị"),
(51,"ST.TD","H. Trần Đề"),
(51,"ST.TP.ST","TP. Sóc Trăng"),
(51,"ST.TX.NN","TX. Ngã Năm"),
(51,"ST.TX.VC","TX. Vĩnh Châu"),
(52,"SL.BY","H. Bắc Yên"),
(52,"SL.MS","H. Mai Sơn"),
(52,"SL.MC","H. Mộc Châu"),
(52,"SL.ML","H. Mường La"),
(52,"SL.PY","H. Phù Yên"),
(52,"SL.QN","H. Quỳnh Nhai"),
(52,"SL.SM","H. Sông Mã"),
(52,"SL.SC","H. Sốp Cộp"),
(52,"SL.TC","H. Thuận Châu"),
(52,"SL.VH","H. Vân Hồ"),
(52,"SL.YC","H. Yên Châu"),
(52,"SL.TP.SL","TP. Sơn La"),
(53,"TN.BC","H. Bến Cầu"),
(53,"TN.CT","H. Châu Thành"),
(53,"TN.DMC","H. Dương Minh Châu"),
(53,"TN.GD","H. Gò Dầu"),
(53,"TN.HT","H. Hòa Thành"),
(53,"TN.TB","H. Tân Biên"),
(53,"TN.TC","H. Tân Châu"),
(53,"TN.TG","H. Trảng Bàng"),
(53,"TN.TP.TN","TP. Tây Ninh"),
(54,"TB.DH","H. Đông Hưng"),
(54,"TB.HH","H. Hưng Hà"),
(54,"TB.KX","H. Kiến Xương"),
(54,"TB.QP","H. Quỳnh Phụ"),
(54,"TB.TT","H. Thái Thụy"),
(54,"TB.TH","H. Tiền Hải"),
(54,"TB.VT","H. Vũ Thư"),
(54,"TB.TP.TB","TP. Thái Bình"),
(55,"THN.DT","H. Đại Từ"),
(55,"THN.DH","H. Định Hóa"),
(55,"THN.DY","H. Đồng Hỷ"),
(55,"THN.PB","H. Phú Bình"),
(55,"THN.PL","H. Phú Lương"),
(55,"THN.VN","H. Võ Nhai"),
(55,"THN.TP.TN","TP. Thái Nguyên"),
(55,"THN.PY","TX. Phổ Yên"),
(55,"THN.TX.SC","TX. Sông Công"),
(56,"TH.BT","H. Bá Thước"),
(56,"TH.CT","H. Cẩm Thủy"),
(56,"TH.DS","H. Đông Sơn"),
(56,"TH.HI","H. Hà Hải"),
(56,"TH.HT","H. Hà Trung"),
(56,"TH.HL","H. Hậu Lộc"),
(56,"TH.HH","H. Hoằng Hóa"),
(56,"TH.LC","H. Lang Chánh"),
(56,"TH.ML","H. Mường Lát"),
(56,"TH.NS","H. Nga Sơn"),
(56,"TH.NL","H. Ngọc Lặc"),
(56,"TH.NT","H. Như Thanh"),
(56,"TH.NX","H. Như Xuân"),
(56,"TH.NC","H. Nông Cống"),
(56,"TH.QH","H. Quan Hóa"),
(56,"TH.QS","H. Quang Sơn"),
(56,"TH.QX","H. Quảng Xương"),
(56,"TH.TT","H. Thạch Thành"),
(56,"TH.TH","H. Thiệu Hóa"),
(56,"TH.TX","H. Thọ Xuân"),
(56,"TH.THX","H. Thường Xuân"),
(56,"TH.TG","H. Tĩnh Gia"),
(56,"TH.TS","H. Triệu Sơn"),
(56,"TH.VL","H. Vĩnh Lộc"),
(56,"TH.YD","H. Yên Định"),
(56,"TH.TP.TH","TP. Thanh Hóa"),
(56,"TH.TX.BS","TX. Bỉm Sơn"),
(56,"TH.TX.SS","TX. Sầm Sơn"),
(57,"TTH.AL","H. A Lưới"),
(57,"TTH.HN","H. Hội An"),
(57,"TTH.ND","H. Nam Đông"),
(57,"TTH.NT","H. Núi Thành"),
(57,"TTH.PD","H. Phong Điền"),
(57,"TTH.PL","H. Phú Lộc"),
(57,"TTH.PV","H. Phú Vang"),
(57,"TTH.QD","H. Quảng Điền"),
(57,"TTH.TP.H","TP. Huế"),
(57,"TTH.TX.HT","TX. Hương Thủy"),
(57,"TTH.TX.HA","TX. Hương Trà"),
(58,"TG.APD","H. An Phú Đông"),
(58,"TG.CB","H. Cái Bè"),
(58,"TG.CL","H. Cai Lậy"),
(58,"TG.CT","H. Châu Thành"),
(58,"TG.CG","H. Chợ Gạo"),
(58,"TG.GCD","H. Gò Công Đông"),
(58,"TG.GCT","H. Gò Công Tây"),
(58,"TG.TPD","H. Tân Phú Đông"),
(58,"TG.TP","H. Tân Phước"),
(58,"TG.TP.MT","TP. Mỹ Tho"),
(58,"TG.TX.CL","TX. Cai Lậy"),
(58,"TG.TX.GC","TX. Gò Công"),
(59,"TV.CL","H. Càng Long"),
(59,"TV.CK","H. Cầu Kè"),
(59,"TV.CN","H. Cầu Ngang"),
(59,"TV.CT","H. Châu Thành"),
(59,"TV.DH","H. Duyên Hải"),
(59,"TV.TC","H. Tiểu Cần"),
(59,"TV.TU","H. Trà Cú"),
(59,"TV.TP.TV","TP. Trà Vinh"),
(60,"TQ.CH","H. Chiêm Hóa"),
(60,"TQ.HY","H. Hàm Yên"),
(60,"TQ.LB","H. Lâm Bình"),
(60,"TQ.NH","H. Na Hang"),
(60,"TQ.SD","H. Sơn Dương"),
(60,"TQ.YS","H. Yên Sơn"),
(60,"TQ.TP.TQ","TP. Tuyên Quang"),
(61,"VL.BT","H. Bình Tân"),
(61,"VL.LH","H. Long Hồ"),
(61,"VL.MT","H. Mang Thít"),
(61,"VL.TB","H. Tam Bình"),
(61,"VL.TO","H. Trà Ôn"),
(61,"VL.VL","H. Vũng Liêm"),
(61,"VL.TP.VL","TP. Vĩnh Long"),
(61,"VL.TX.BM","TX. Bình Minh"),
(62,"VP.BX","H. Bình Xuyên"),
(62,"VP.LT","H. Lập Thạch"),
(62,"VP.ML","H. Mê Linh"),
(62,"VP.SL","H. Sông Lô"),
(62,"VP.TAD","H. Tam Đảo"),
(62,"VP.TD","H. Tam Dương"),
(62,"VP.VT","H. Vĩnh Tường"),
(62,"VP.YL","H. Yên Lạc"),
(62,"VP.TP.VY","TP. Vĩnh Yên"),
(62,"VP.TX.PY","TX. Phúc Yên"),
(63,"YB.LY","H. Lục Yên"),
(63,"YB.MCC","H. Mù Căng Chải"),
(63,"YB.TT","H. Trạm Tấu"),
(63,"YB.TY","H. Trấn Yên"),
(63,"YB.VC","H. Văn Chấn"),
(63,"YB.VY","H. Văn Yên"),
(63,"YB.YB","H. Yên Bình"),
(63,"YB.TP.YB","TP. Yên Bái"),
(63,"YB.TX.NL","TX. Nghĩa Lộ");